name: _

on:
  workflow_call:
    inputs: 
      createrelease:
        type: boolean
        default: false
        required: false 
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            qthost: windows
            qtarch: win64_msvc2019_64
            version: 6.8.2.1
            pythonversion: 3.9.19
            arch: x64
            binding: PySide6
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: jurplel/install-qt-action@v4
        with:
          version: ${{matrix.version}}
          arch: ${{matrix.qtarch}}
          host: ${{matrix.qthost}}
          target: desktop
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.pythonversion}}
          architecture: ${{ matrix.arch }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12.10
          architecture: x64
      
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
        with:
          arch: ${{ matrix.arch }}
      - run: python scripts/dobuild.py ${{matrix.pythonversion}} ${{ matrix.qtarch }}  ${{ matrix.version }} ${{ matrix.arch }}  ${{matrix.binding}}
      - uses: actions/attest-build-provenance@v2.2.0
        with:
            subject-path: scripts/objects
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.qthost}}_${{ matrix.binding }}_${{ matrix.arch }}
          path: scripts/objects
